name: Security Scanning

on:
  push:
    branches: [ main, master, feat/* ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  bandit:
    name: Run Bandit Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -c pyproject.toml -r src/

  trivy:
    name: Run Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (FS mode)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
